### ISSUE TITLE
Consider file resolution instead of filesize

### ISSUE THREAD

**Issue by meganukebmp** [rif/imgdup2go#4]
Currently the way this selects the best match is by picking the biggest filesize. This fails to properly pick the right file when there is a library with mixed formats such as jpegs and pngs. The png format might have a lower resolution or simply be a convert from a jpeg and not necessarily carry more image information. The tool should compare image resolutions instead to decide which file to keep.

**Comment by rif** [comment]
Very good suggestion, thank you.

Just released v2.1.0, please check it out!
